version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: manchester_seals_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: manchester_seals
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  api:
    build: .
    container_name: manchester_seals_api
    ports:
      - "5100:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/
      DB_NAME: manchester_seals
      FLASK_DEBUG: "True"
      PORT: "5000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network
    command: python app.py

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge

